export const GLOBAL_BUILDING_TYPES = {
    NONE: "NONE",
    POWER_CENTER: "POWER_CENTER",
    ROAD: "ROAD",
    EXTERNAL_BUILDING: "EXTERNAL_BUILDING",
};
export const POWER_CENTER_TIERS = {
    ZERO: 0,
    FIRST: 1,
    SECOND: 2,
};
export const POWER_CENTER_MAX_TIER = POWER_CENTER_TIERS.SECOND;

export const EXTERNAL_BUILDING_TYPE_NAMES = {
    FARM: "FARM",
    WOODCUTTER: "WOODCUTTER",
    STONE_QUARRY: "STONE_QUARRY",
    SAWMILL: "SAWMILL",
};

export const INTERNAL_BUILDING_TYPE_NAMES = {
    // ACTION
    COLONIZATION_CENTER: "COLONIZATION_CENTER",
    GUILD: "GUILD",
    MARKET: "MARKET",

    // BONUS
    WORKSHOP: "WORKSHOP",
    WAREHOUSE: "WAREHOUSE",
    TAX_OFFICE: "TAX_OFFICE",
};
