export const AUTH_SERVICE_STATES = {
    IDLE: "IDLE",
    TRY_DESCRIBE: "TRY_DESCRIBE",
    USER_LOGGED: "USER_LOGGED",
    USER_NOT_LOGGED: "USER_NOT_LOGGED",
};

export const AUTH_SERVICE_ACTIONS = {
    DESCRIBE: "DESCRIBE",
    IS_DESCRIBED: "IS_DESCRIBED",
    IS_NOT_DESCRIBED: "IS_NOT_DESCRIBED",
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGOUT: "LOGOUT",
};
