export const GAME_ACTIONS = {
    START_BUILD_POWER_CENTER: "START_BUILD_POWER_CENTER",
    START_DESTROY_POWER_CENTER: "START_DESTROY_POWER_CENTER",

    START_BUILD_ROAD: "START_BUILD_ROAD",
    START_DESTROY_ROAD: "START_DESTROY_ROAD",

    START_BUILD_EXTERNAL_BUILDING: "START_BUILD_EXTERNAL_BUILDING",
    START_DESTROY_EXTERNAL_BUILDING: "START_DESTROY_EXTERNAL_BUILDING",

    START_BUILD_INTERNAL_BUILDING: "START_BUILD_INTERNAL_BUILDING",

    CREATE_TRADE_ROUTE: "CREATE_TRADE_ROUTE",
    INCREASE_TRADE_ROUTE_PRIORITY: "INCREASE_TRADE_ROUTE_PRIORITY",
    DECREASE_TRADE_ROUTER_PRIORITY: "DECREASE_TRADE_ROUTER_PRIORITY",
    DESTROY_TRADE_ROUTE: "DESTROY_TRADE_ROUTE",
};

export const GAME_VALIDATIONS = {
    CAN_BUILD_POWER_CENTER: "CAN_BUILD_POWER_CENTER",
    CAN_PLACE_POWER_CENTER: "CAN_PLACE_POWER_CENTER",

    CAN_BUILD_ROAD: "CAN_BUILD_ROAD",
    CAN_PLACE_ROAD: "CAN_PLACE_ROAD",
    CAN_DESTROY_PLACED_ROAD: "CAN_DESTROY_PLACED_ROAD",

    CAN_BUILD_EXTERNAL_BUILDING: "CAN_BUILD_EXTERNAL_BUILDING",
    CAN_PLACE_EXTERNAL_BUILDING: "CAN_PLACE_EXTERNAL_BUILDING",
    CAN_DESTROY_PLACED_EXTERNAL_BUILDING: "CAN_DESTROY_PLACED_EXTERNAL_BUILDING",

    CAN_BUILD_INTERNAL_BUILDING: "CAN_BUILD_INTERNAL_BUILDING",

    CAN_CREATE_TRADE_ROUTE: "CAN_CREATE_TRADE_ROUTE",
    CAN_SEND_TRADE_ROUTE: "CAN_SEND_TRADE_ROUTE",
};
