export const GAME_ACTIONS = {
    START_BUILD_POWER_CENTER: "START_BUILD_POWER_CENTER",
    START_DESTROY_POWER_CENTER: "START_DESTROY_POWER_CENTER",

    START_BUILD_ROAD: "START_BUILD_ROAD",
    START_DESTROY_ROAD: "START_DESTROY_ROAD",

    START_BUILD_EXTERNAL_BUILDING: "START_BUILD_EXTERNAL_BUILDING",
    START_DESTROY_EXTERNAL_BUILDING: "START_DESTROY_EXTERNAL_BUILDING",

    START_BUILD_INTERNAL_BUILDING: "START_BUILD_INTERNAL_BUILDING",
};

export const GAME_VALIDATIONS = {
    CAN_BUILD_POWER_CENTER: "CAN_BUILD_POWER_CENTER",
    CAN_BUILD_ROAD: "CAN_BUILD_ROAD",
    CAN_PLACE_ROAD: "CAN_PLACE_ROAD",
    CAN_REMOVE_PLACED_ROAD: "CAN_REMOVE_PLACED_ROAD",
    CAN_PLACE_POWER_CENTER: "CAN_PLACE_POWER_CENTER",
};
