import { areaTypes, biomTypes } from "models/map";
import { SPRITESHEET_BIOM_NAMES, SPRITESHEET_POWER_CENTER_NAMES } from "../constants";

export const AREA_TYPE_TO_BIOM_SPRITESHEET_NAME = {
    [areaTypes.NONE]: {
        [biomTypes.DESERT]: SPRITESHEET_BIOM_NAMES.DESERT,
        [biomTypes.FLATLAND]: SPRITESHEET_BIOM_NAMES.FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_BIOM_NAMES.GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_BIOM_NAMES.TUNDRA,
        [biomTypes.JUNGLE]: SPRITESHEET_BIOM_NAMES.JUNGLE,
    },
    [areaTypes.HILLS]: {
        [biomTypes.DESERT]: SPRITESHEET_BIOM_NAMES.HILLS_DESERT,
        [biomTypes.FLATLAND]: SPRITESHEET_BIOM_NAMES.HILLS_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_BIOM_NAMES.HILLS_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_BIOM_NAMES.HILLS_TUNDRA,
    },
    [areaTypes.FOREST]: {
        [biomTypes.FLATLAND]: SPRITESHEET_BIOM_NAMES.FOREST_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_BIOM_NAMES.FOREST_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_BIOM_NAMES.FOREST_TUNDRA,
    },
    [areaTypes.FOREST_HILLS]: {
        [biomTypes.FLATLAND]: SPRITESHEET_BIOM_NAMES.FOREST_HILLS_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_BIOM_NAMES.FOREST_HILLS_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_BIOM_NAMES.FOREST_HILLS_TUNDRA,
    },
};

export const AREA_TYPE_TO_POWER_CENTER_SPRITESHEET_NAME = {
    [areaTypes.NONE]: {
        [biomTypes.DESERT]: SPRITESHEET_POWER_CENTER_NAMES.DESERT,
        [biomTypes.FLATLAND]: SPRITESHEET_POWER_CENTER_NAMES.FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_POWER_CENTER_NAMES.GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_POWER_CENTER_NAMES.TUNDRA,
        // [biomTypes.JUNGLE]: SPRITESHEET_POWER_CENTER_NAMES.JUNGLE,
    },
    [areaTypes.HILLS]: {
        [biomTypes.DESERT]: SPRITESHEET_POWER_CENTER_NAMES.HILLS_DESERT,
        [biomTypes.FLATLAND]: SPRITESHEET_POWER_CENTER_NAMES.HILLS_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_POWER_CENTER_NAMES.HILLS_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_POWER_CENTER_NAMES.HILLS_TUNDRA,
    },
    [areaTypes.FOREST]: {
        [biomTypes.FLATLAND]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_TUNDRA,
    },
    [areaTypes.FOREST_HILLS]: {
        [biomTypes.FLATLAND]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_HILLS_FLATLAND,
        [biomTypes.GRASSLAND]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_HILLS_GRASSLAND,
        [biomTypes.TUNDRA]: SPRITESHEET_POWER_CENTER_NAMES.FOREST_HILLS_TUNDRA,
    },
};
