export const PLAYER_VALUES = {
    INITIAL_TREASURE: 100,
};

export const REGION_VALUES = {
    INITIAL_PROVISION: 10,
    PROVISION_INCREASING_DELTA: 10,
};

export const POWER_CENTER_VALUES = {
    INITIAL_COST: 100,
    TICKS_BUILD_TIME: 5,
    TICKS_DESTROY_TIME: 5,
};
