export const GAME_ACTIONS = {
    START_BUILD_POWER_CENTER: "START_BUILD_POWER_CENTER",
    START_BUILD_ROAD: "START_BUILD_ROAD",
    START_DESTROY_ROAD: "START_DESTROY_ROAD",
};

export const REQUIRES_ON_MAP_CONFIRMATION_GAME_ACTIONS = [
    GAME_ACTIONS.START_BUILD_POWER_CENTER,
    GAME_ACTIONS.START_BUILD_ROAD,
    GAME_ACTIONS.START_DESTROY_ROAD,
];
