export const GAME_VALIDATIONS = {
    CAN_BUILD_POWER_CENTER: "CAN_BUILD_POWER_CENTER",
    CAN_BUILD_ROAD: "CAN_BUILD_ROAD",
    CAN_PLACE_ROAD: "CAN_PLACE_ROAD",
    CAN_REMOVE_PLACED_ROAD: "CAN_REMOVE_PLACED_ROAD",
    CAN_PLACE_POWER_CENTER: "CAN_PLACE_POWER_CENTER",
};
