export const GLOBAL_BUILDING_TYPES = {
    NONE: "NONE",
    POWER_CENTER: "POWER_CENTER",
    ROAD: "ROAD",
    OUTER_BUILDING: "OUTER_BUILDING",
};

export const OUTER_BUILDING_TYPES = {
    STONE_QUARRY: "STONE_QUARRY",
    WOODCUTTER: "WOODCUTTER",
    SAWMILL: "SAWMILL",
    FARM: "FARM",
};

export const POWER_CENTER_TIERS = {
    FIRST: "FIRST",
    SECOND: "SECOND",
};
